main:
  - name: About
    url: '#about'
    weight: 1
  - name: Posts
    url: /posts/
    weight: 2
  - name: GitHub
    url: https://github.com/pshef
    weight: 3
  - name: Twitter
    url: https://twitter.com/pshef5
    weight: 4
  - name: LinkedIn
    url: https://linkedin.com/in/christopher-h-pshef
    weight: 5
